// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp3cW21ojgOIAStn_ujLTa7A5selvZTy8',
    appId: '1:8306330866:web:821efef2b0f802c524146b',
    messagingSenderId: '8306330866',
    projectId: 'instagram-clone-57eea',
    authDomain: 'instagram-clone-57eea.firebaseapp.com',
    storageBucket: 'instagram-clone-57eea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_ZVZZtq2ttd_19YAyrqUVuY1bkCY4GLk',
    appId: '1:8306330866:android:cb3a45d7c930d52624146b',
    messagingSenderId: '8306330866',
    projectId: 'instagram-clone-57eea',
    storageBucket: 'instagram-clone-57eea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ8-UNh8TH3A_9Ht8Wq7ZFtMN4UXcRIlQ',
    appId: '1:8306330866:ios:d97360c2a9404ce424146b',
    messagingSenderId: '8306330866',
    projectId: 'instagram-clone-57eea',
    storageBucket: 'instagram-clone-57eea.appspot.com',
    iosClientId: '8306330866-sauu79u0iid7t8madjv11kml6vldsfrk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterInstagram',
  );
}
